<?php

return [
    [
        'id' => 'chocolate-cake',
        'name' => 'Chocolate Cake',
        'price' => 570,
        'category' => 'cakes',
        'image' => 'images/choco_cake.png',
        'reviews' => 964,
        'rating' => 5,
        'featured' => 1,
        'description' => 'A rich, moist chocolate cake layered with silky ganache. Perfect for birthdays, celebrations, or when you simply need a chocolate moment.',
        'details' => 'Made with Dutch-process cocoa and finished with a smooth chocolate frosting. Available for same-day pickup when ordered before 11:00 AM.',
    ],
    [
        'id' => 'red-velvet-cookie',
        'name' => 'Red Velvet Cookie',
        'price' => 45,
        'category' => 'cookies',
        'image' => 'images/red_cookies.png',
        'reviews' => 1369,
        'rating' => 5,
        'featured' => 1,
        'description' => 'Soft-baked red velvet cookies with a hint of cocoa and a cream cheese drizzle. Chewy in the center, lightly crisp at the edges.',
        'details' => 'Baked fresh every morning. Best enjoyed the same day, or stored in an airtight container for up to 3 days.',
    ],
    [
        'id' => 'strawberry-cupcake',
        'name' => 'Strawberry Cupcake',
        'price' => 50,
        'category' => 'cupcakes',
        'image' => 'images/berry_cupcake.png',
        'reviews' => 1587,
        'rating' => 5,
        'featured' => 1,
        'description' => 'Fluffy vanilla cupcakes topped with strawberry buttercream and a fresh berry finish. Light, sweet, and made for sharing.',
        'details' => 'Each cupcake is piped to order. Custom color frosting is available when you add a note at checkout.',
    ],
    [
        'id' => 'croissant',
        'name' => 'Croissant',
        'price' => 80,
        'category' => 'breads',
        'image' => 'images/croissant-.png',
        'reviews' => 853,
        'rating' => 5,
        'featured' => 1,
        'description' => 'Classic butter croissants with delicate, flaky layers. Baked until golden and served warm from the oven.',
        'details' => 'Laminated dough, folded by hand. Pair it with coffee or enjoy it plain — it needs nothing else.',
    ],
    [
        'id' => 'black-forest-cake',
        'name' => 'Black Forest Cake',
        'price' => 620,
        'category' => 'cakes',
        'image' => 'images/dark choco.png',
        'reviews' => 742,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Dark chocolate sponge layered with cream and cherries. A bakery classic with a homemade finish.',
        'details' => 'Finished with chocolate shavings. Please order at least 1 day ahead for whole cakes.',
    ],
    [
        'id' => 'vanilla-cake',
        'name' => 'Ube Cake',
        'price' => 520,
        'category' => 'cakes',
        'image' => 'images/ube cake.png',
        'reviews' => 611,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Soft ube sponge with a creamy ube frosting. A vibrant purple cake made for celebrations.',
        'details' => 'Made with real ube. Add a dedication message during checkout or through Build Your Own.',
    ],
    [
        'id' => 'classic-chocolate-cake',
        'name' => 'Classic Chocolate Layer',
        'price' => 540,
        'category' => 'cakes',
        'image' => 'images/classic choco layer.png',
        'reviews' => 488,
        'rating' => 4,
        'featured' => 0,
        'description' => 'Everyday chocolate cake with a homemade crumb and cocoa frosting. Comforting and familiar.',
        'details' => 'Great as a 6-inch celebration cake. Please note allergens: wheat, eggs, dairy.',
    ],
    [
        'id' => 'banana-bread',
        'name' => 'Banana Bread',
        'price' => 120,
        'category' => 'breads',
        'image' => 'images/banana_bread.png',
        'reviews' => 390,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Moist banana bread baked with ripe bananas and a hint of cinnamon. Sliced and ready to enjoy.',
        'details' => 'Sold by the loaf. Toast it lightly and add butter for the full bakery experience.',
    ],
    [
        'id' => 'butter-croissant',
        'name' => 'Raspberry Croissant',
        'price' => 85,
        'category' => 'breads',
        'image' => 'images/rasberry croissant.png',
        'reviews' => 276,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Flaky butter croissant filled with raspberry jam. Crisp outside, tender inside, with a bright berry finish.',
        'details' => 'Limited batches each morning. We recommend ordering early for weekend pickup.',
    ],
    [
        'id' => 'cinnamon-loaf',
        'name' => 'Cinnamon Sugar Loaf',
        'price' => 95,
        'category' => 'breads',
        'image' => 'images/cinnamon sugar loaf.png',
        'reviews' => 214,
        'rating' => 4,
        'featured' => 0,
        'description' => 'Soft loaf swirled with cinnamon sugar. A breakfast favorite and an easy gift.',
        'details' => 'Best within 2 days of baking. We can wrap it for gifting at pickup.',
    ],
    [
        'id' => 'chocolate-chip-cookie',
        'name' => 'Chocolate Chip Cookie',
        'price' => 40,
        'category' => 'cookies',
        'image' => 'images/chocolate_chip_cookie.png',
        'reviews' => 1024,
        'rating' => 5,
        'featured' => 0,
        'description' => 'The classic: brown-butter dough, melted chocolate pools, and a chewy center.',
        'details' => 'Available by the piece or as a half-dozen box at checkout notes.',
    ],
    [
        'id' => 'sugar-cookie',
        'name' => 'Soft Sugar Cookie',
        'price' => 35,
        'category' => 'cookies',
        'image' => 'images/soft sugar cookie.png',
        'reviews' => 318,
        'rating' => 4,
        'featured' => 0,
        'description' => 'Tender sugar cookies with a light vanilla finish. Simple, sweet, and nostalgic.',
        'details' => 'A favorite with kids. Ask us about custom icing colors for parties.',
    ],
    [
        'id' => 'double-chocolate-cookie',
        'name' => 'Smores Cookie',
        'price' => 48,
        'category' => 'cookies',
        'image' => 'images/smores cookie.png',
        'reviews' => 455,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Cocoa cookie dough loaded with chocolate chips. For serious chocolate cravings.',
        'details' => 'Slightly crisp edge, fudgy middle. Pairs well with cold milk or hot chocolate.',
    ],
    [
        'id' => 'chocolate-cupcake',
        'name' => 'Chocolate Cupcake',
        'price' => 50,
        'category' => 'cupcakes',
        'image' => 'images/chocolate_cupcake.png',
        'reviews' => 701,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Moist chocolate cupcakes topped with chocolate buttercream. Small size, big flavor.',
        'details' => 'Sold individually. Mix-and-match boxes are welcome — just add a checkout note.',
    ],
    [
        'id' => 'vanilla-cupcake',
        'name' => 'Vanilla Cupcake',
        'price' => 45,
        'category' => 'cupcakes',
        'image' => 'images/vannila_cupcake.png',
        'reviews' => 529,
        'rating' => 4,
        'featured' => 0,
        'description' => 'Classic vanilla cupcake with a swirl of vanilla frosting. Clean, light, and crowd-pleasing.',
        'details' => 'A reliable party staple. We can add sprinkles if you mention it in your order notes.',
    ],
    [
        'id' => 'red-velvet-cupcake',
        'name' => 'Red Velvet Cupcake',
        'price' => 55,
        'category' => 'cupcakes',
        'image' => 'images/red_velvet_cupcake.png',
        'reviews' => 812,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Red velvet cupcakes with cream cheese frosting. A little tangy, a little sweet.',
        'details' => 'Our most requested cupcake for events. Please order a dozen or more 1 day in advance.',
    ],
    [
        'id' => 'custom-cake',
        'name' => 'Custom Cake',
        'price' => 450,
        'category' => 'cakes',
        'image' => 'images/dark choco.png',
        'reviews' => 0,
        'rating' => 5,
        'featured' => 0,
        'description' => 'Build your own cake with a chosen flavor, size, and dedication.',
        'details' => 'Priced by size. Used internally for custom cake orders.',
    ],
];
